os: linux
language: node_js
node_js:
  - "10"
cache: yarn

# platform specific configuration
jobs:
  include:
    - name: "Standalone MacOS"
      os: osx
      before_install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install git-lfs
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install ffmpeg
      script: 
        - cd gulp
        - yarn gulp build.standalone-prod
        - yarn gulp standalone.prepare
        - yarn gulp standalone.package.prod.darwin64

    - name: "Standalone Linux"
      os: linux
      before_install:
        # git lfs is already installed
        - sudo apt-get install libavformat-dev libavfilter-dev libavdevice-dev ffmpeg
      script: 
        - cd gulp
        - yarn gulp build.standalone-prod
        - yarn gulp standalone.prepare
        - yarn gulp standalone.package.prod.linux64
        - yarn gulp standalone.package.prod.linux32

    - name: "Standalone Windows"
      os: windows
      before_install:
        - choco install git-lfs -y -f | echo "0" # choco fails but git-lfs is still installed
        - choco install ffmpeg
        - export PATH=/ProgramData/chocolatey/lib/ffmpeg/tools/ffmpeg/bin:$PATH
  
      script:
        - cd gulp
        - yarn gulp build.standalone-prod
        - yarn gulp standalone.prepare
        - yarn gulp standalone.package.prod.win64
        - yarn gulp standalone.package.prod.win32

# shared
install:
  - git lfs install
  - git lfs pull

  - yarn
  
  # electron dependencies
  - cd electron 
  - yarn
  - cd ..

  # gulp dependendencies
  - cd gulp 
  - yarn
  - cd ..
