# validate config at https://config.travis-ci.com/explore
os: linux
dist: xenial
language: node_js
node_js:
  - "10"
cache: yarn

# platform specific configuration
jobs:

  # jobs which have to succeed
  include:
    # OS: MAC
    ## -> build darwin
    - name: "MacOS: Standalone MacOS"
      os: osx
      osx_image: xcode11.3
      before_install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install git-lfs
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install ffmpeg
      script: 
        - cd gulp
        - yarn gulp build.standalone-prod || travis_terminate 1
        - yarn gulp standalone.prepare
        - yarn gulp standalone.package.prod.darwin64
        - cd ..
      after_success:
        - ls tmp_standalone_files
        - cd tmp_standalone_files/shapez.io-standalone-darwin-x64
        - zip -rX shapezio-mac.zip .
        - cd ../..
      addons:
        artifacts:
          paths:
            - ./tmp_standalone_files/shapez.io-standalone-darwin-x64/shapezio-mac.zip

    ## -> build win
    - name: "MacOS: Standalone Windows"
      os: osx
      osx_image: xcode11.3
      before_install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install git-lfs
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install ffmpeg
        - HOMEBREW_NO_AUTO_UPDATE=1 brew cask install wine-stable
        # prevent Wine popup dialogs about installing additional packages
        - export WINEDLLOVERRIDES="mscoree,mshtml="
        - export WINEDEBUG="-all"
      script:
        - cd gulp
        - yarn gulp build.standalone-prod || travis_terminate 1
        - yarn gulp standalone.prepare
        - yarn gulp standalone.package.prod.win64
        - yarn gulp standalone.package.prod.win32
        - cd ..
      after_success:
        - ls tmp_standalone_files
        - cd tmp_standalone_files/shapez.io-standalone-win32-x64
        - zip -rX shapezio-windows.zip .
        - cd ../..
      addons:
        artifacts:
          paths:
            - ./tmp_standalone_files/shapez.io-standalone-win32-x64/shapezio-windows.zip

    ## -> build linux
    - name: "MacOS: Standalone Linux"
      os: osx
      osx_image: xcode11.3
      before_install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install git-lfs
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install ffmpeg
      script: 
        - cd gulp
        - yarn gulp build.standalone-prod || travis_terminate 1
        - yarn gulp standalone.prepare
        - yarn gulp standalone.package.prod.linux64
        - yarn gulp standalone.package.prod.linux32
        - cd ..
      after_success:
        - ls tmp_standalone_files
        - cd tmp_standalone_files/shapez.io-standalone-linux-x64
        - zip -rX shapezio-linux.zip .
        - cd ../..
      addons:
        artifacts:
          paths:
            - ./tmp_standalone_files/shapez.io-standalone-linux-x64/shapezio-linux.zip

    # OS: LINUX
    ## -> build darwin
    ## not possible

    ## -> build win
    - name: "Linux: Standalone Windows"
      os: linux
      addons:
        apt:
          packages:
            - libavformat-dev
            - libavfilter-dev
            - libavdevice-dev
            - ffmpeg
            - wine
        artifacts:
          paths:
            - ./tmp_standalone_files/shapez.io-standalone-win32-x64/shapezio-windows.zip
      script: 
        - cd gulp
        - yarn gulp build.standalone-prod || travis_terminate 1
        - yarn gulp standalone.prepare
        - yarn gulp standalone.package.prod.win64
        - yarn gulp standalone.package.prod.win32
        - cd ..
      after_success:
        - cd tmp_standalone_files/shapez.io-standalone-win32-x64
        - zip -rX shapezio-windows.zip .
        - cd ../..

    ## -> build linux
    - name: "Linux: Standalone Linux"
      os: linux
      addons:
        apt:
          packages:
            - libavformat-dev
            - libavfilter-dev
            - libavdevice-dev
            - ffmpeg
        artifacts:
          paths:
            - ./tmp_standalone_files/shapez.io-standalone-linux-x64/shapezio-linux.zip
      script: 
        - cd gulp
        - yarn gulp build.standalone-prod || travis_terminate 1
        - yarn gulp standalone.prepare
        - yarn gulp standalone.package.prod.linux64
        - yarn gulp standalone.package.prod.linux32
        - cd ..
      after_success:
        - ls tmp_standalone_files
        - cd tmp_standalone_files/shapez.io-standalone-linux-x64
        - zip -rX shapezio-linux.zip .
        - cd ../..

    # OS: WINDOWS
    ## -> build darwin
    ## not possible

    ## -> build win
    - name: "Windows: Standalone Windows"
      os: windows
      env: YARN_GPG=no
      before_install:
        - choco install git-lfs -y -f || echo "0" # choco fails but git-lfs is still installed
        - choco install ffmpeg
        - export PATH=/C/ProgramData/chocolatey/lib/ffmpeg/tools/ffmpeg/bin:$PATH
        - wget https://github.com/moiamond/docker-ffmpeg-base-windowsservercore/raw/master/System32/avicap32.dll -P /C/Windows/System32/
        - wget https://github.com/moiamond/docker-ffmpeg-base-windowsservercore/raw/master/System32/msvfw32.dll -P /C/Windows/System32/
      script:
        - cd gulp
        - yarn gulp build.standalone-prod || travis_terminate 1
        - yarn gulp standalone.prepare
        - yarn gulp standalone.package.prod.win64
        - yarn gulp standalone.package.prod.win32
        - cd ..
      after_success:
        - dir tmp_standalone_files
        - cd tmp_standalone_files/shapez.io-standalone-win32-x64
        - 7z a shapezio-windows.zip "*.*"
        - cd ../..
      addons:
        artifacts:
          paths:
            - ./tmp_standalone_files/shapez.io-standalone-win32-x64/shapezio-windows.zip

    ## -> build linux
    - name: "Windows: Standalone Linux"
      os: windows
      env: YARN_GPG=no
      before_install:
        - choco install git-lfs -y -f || echo "0" # choco fails but git-lfs is still installed
        - choco install ffmpeg
        - export PATH=/C/ProgramData/chocolatey/lib/ffmpeg/tools/ffmpeg/bin:$PATH
        - wget https://github.com/moiamond/docker-ffmpeg-base-windowsservercore/raw/master/System32/avicap32.dll -P /C/Windows/System32/
        - wget https://github.com/moiamond/docker-ffmpeg-base-windowsservercore/raw/master/System32/msvfw32.dll -P /C/Windows/System32/
      script:
        - cd gulp
        - yarn gulp build.standalone-prod || travis_terminate 1
        - yarn gulp standalone.prepare
        - yarn gulp standalone.package.prod.linux64
        - yarn gulp standalone.package.prod.linux32
        - cd ..
      after_success:
        - dir tmp_standalone_files
        - cd tmp_standalone_files/shapez.io-standalone-linux-x64
        - 7z a shapezio-linux.zip "*.*"
        - cd ../..
      addons:
        artifacts:
          paths:
            - ./tmp_standalone_files/shapez.io-standalone-linux-x64/shapezio-linux.zip

  # mark build as finished even if "allow_failures" are still running
  fast_finish: true

  # optional jobs which may fail
  allow_failures:
    - name: "MacOS: Standalone MacOS"
    - name: "MacOS: Standalone Windows" 
    - name: "MacOS: Standalone Linux"
    - name: "Linux: Standalone Windows"
    - name: "Linux: Standalone Linux"
    - name: "Windows: Standalone Windows"
    - name: "Windows: Standalone Linux"

# shared
install:
  - git lfs install
  - git lfs pull

  - yarn
  
  # electron dependencies
  - cd electron 
  - yarn
  - cd ..

  # gulp dependendencies
  - cd gulp 
  - yarn
  - cd ..
