# based on electron-packager before-install.sh
os: osx
language: node_js
node_js:
  - "10"
cache: yarn

install:
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install git-lfs

  - git lfs install
  - git lfs pull

  - yarn
  
  # electron dependencies
  - cd electron 
  - yarn
  - cd ..

  # gulp dependendencies
  - cd gulp 
  - yarn
  - cd ..

  # works
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install ffmpeg
  
script: 
  - cd gulp
  - yarn gulp build.standalone-prod
  - yarn gulp standalone.prepare
  - yarn gulp standalone.package.prod.darwin64
