# validate config at https://config.travis-ci.com/explore
os: linux
dist: xenial
language: node_js
node_js:
  - "10"
cache: yarn

# platform specific configuration
jobs:

  # jobs which have to succeed
  include:
    # OS: MAC
    - name: "Standalone MacOS on MacOS"
      os: osx
      before_install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install git-lfs
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install ffmpeg
      script: 
        - cd gulp
        - yarn gulp build.standalone-prod
        - yarn gulp standalone.prepare
        - yarn gulp standalone.package.prod.darwin64

    #- name: "Standalone Windows on MacOS"
    #  os: osx
    #  before_install:
    #    - HOMEBREW_NO_AUTO_UPDATE=1 brew install git-lfs
    #    - HOMEBREW_NO_AUTO_UPDATE=1 brew install ffmpeg
    #    - HOMEBREW_NO_AUTO_UPDATE=1 brew cask install wine-stable
    #  script:
    #    - cd gulp
    #    - yarn gulp build.standalone-prod
    #    - yarn gulp standalone.prepare
    #    - yarn gulp standalone.package.prod.win64

    - name: "Standalone Linux on MacOS"
      os: osx
      before_install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install git-lfs
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install ffmpeg
      script: 
        - cd gulp
        - yarn gulp build.standalone-prod
        - yarn gulp standalone.prepare
        - yarn gulp standalone.package.prod.linux64
        - yarn gulp standalone.package.prod.linux32

    # OS: LINUX
    - name: "Standalone Linux on Linux"
      os: linux
      before_install:
        # git lfs is already installed
        - sudo apt-get install libavformat-dev libavfilter-dev libavdevice-dev ffmpeg
      script: 
        - cd gulp
        - yarn gulp build.standalone-prod
        - yarn gulp standalone.prepare
        - yarn gulp standalone.package.prod.linux64
        - yarn gulp standalone.package.prod.linux32

    - name: "Standalone Windows on Linux"
      os: linux
      before_install:
        # git lfs is already installed
        - sudo apt-get install libavformat-dev libavfilter-dev libavdevice-dev ffmpeg
        - sudo apt-get install wine
      script: 
        - cd gulp
        - yarn gulp build.standalone-prod
        - yarn gulp standalone.prepare
        - yarn gulp standalone.package.prod.win64
        - yarn gulp standalone.package.prod.win32

    # OS: WINDOWS
    - name: "Standalone Windows on Windows"
      os: windows
      env: YARN_GPG=no
      before_install:
        - choco install git-lfs -y -f || echo "0" # choco fails but git-lfs is still installed
        - choco install ffmpeg
        - export PATH=/ProgramData/chocolatey/lib/ffmpeg/tools/ffmpeg/bin:$PATH
  
      script:
        - cd gulp
        - yarn gulp build.standalone-prod || travis_terminate 1
        - yarn gulp standalone.prepare
        - yarn gulp standalone.package.prod.win64
        - yarn gulp standalone.package.prod.win32
        - travis_terminate 0

  # mark build as finished even if "allow_failures" are still running
  fast_finish: true

  # optional jobs which may fail
  allow_failures:
    - name: "Standalone Windows on Windows"
    - name: "Standalone Windows on MacOS"

# shared
install:
  - git lfs install
  - git lfs pull

  - yarn
  
  # electron dependencies
  - cd electron 
  - yarn
  - cd ..

  # gulp dependendencies
  - cd gulp 
  - yarn
  - cd ..
